### ISSUE TITLE
chunksLeft.padStart is not a function

### ISSUE THREAD

**Issue by rhergenreder** [nesk/rialto#16]
Hello,
i came across an issue when using [puphpeteer](https://github.com/nesk/puphpeteer/), which is probably caused by rialto:

```
use Nesk\Puphpeteer\Puppeteer;
$puppeteer = new Puppeteer;
```

Runnig this php code, produces the following php errors:
```
<br />
<b>Fatal error</b>:  Uncaught Nesk\Rialto\Exceptions\Node\FatalException: chunksLeft.padStart is not a function in (...)/vendor/nesk/rialto/src/ProcessSupervisor.php:307
Stack trace:
#0 (...)/vendor/nesk/rialto/src/ProcessSupervisor.php(387): Nesk\Rialto\ProcessSupervisor-&gt;checkProcessStatus()
#1 (...)/vendor/nesk/rialto/src/ProcessSupervisor.php(167): Nesk\Rialto\ProcessSupervisor-&gt;executeInstruction(Object(Nesk\Rialto\Instruction), false)
#2 (...): Nesk\Rialto\ProcessSupervisor-&gt;__destruct()
#5 {main}
  thrown in <b>(...)/vendor/nesk/rialto/src/ProcessSupervisor.php</b> on line <b>307</b><br />
```

The error is probably referred to [/src/node-process/Connection.js#L112](https://github.com/nesk/rialto/blob/master/src/node-process/Connection.js#L112)

**Comment by rhergenreder** [comment]
Oh this was my fault, upgrading node to at least *8.0* solves this issue. 
See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart#Browser_compatibility
